### ISSUE TITLE
Affix search does not handle empty string

### ISSUE THREAD

**Issue by Adrymne** [JimmyS24/PSO2-Affix-Simulator#12]
Deleting the contents of the search box does not update the affixes displayed.

On a side note, it would be nice if the expansion state of the affix groupings persisted between searches (or just started out in the expanded state).

**Comment by JimmyS24** [comment]
https://github.com/JimmyS24/PSO2-Affix-Simulator/commit/df36d3f0bb25e6281e4050224b14efc3d40da079 should fix it. Thou a lot of testing will be needed to make sure it is working.
